import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.text.SimpleDateFormat;

public class V2Adapter implements V1Sensors{
    V2Sensors ts4;

    public V2Adapter(){
        ts4 = new TS4();
    }

    @Override
    public double getTemp(LocalDate date, LocalTime time){
        LocalTime pstTime = time.minusHours(3); //EST to PST conversion

        DateTimeFormatter formatMyYear = DateTimeFormatter.ofPattern("yyyy"); //seperate year from date
        DateTimeFormatter formatMyMonth = DateTimeFormatter.ofPattern("MM"); //seperate month from date
        DateTimeFormatter formatMyDay = DateTimeFormatter.ofPattern("dd"); //seperate day from date
        DateTimeFormatter formatMyTime = DateTimeFormatter.ofPattern("hh:mm:ss"); //seperate time from time
        DateTimeFormatter formatWhen = DateTimeFormatter.ofPattern("a"); //seperate am or pm generated by time from time

        String formattedYear = date.format(formatMyYear);
        String formattedMonth = date.format(formatMyMonth);
        String formattedDay = date.format(formatMyDay);

        String formattedTime = pstTime.format(formatMyTime);
        String formattedWhen = pstTime.format(formatWhen);

        //System.out.println(formattedYear +" "+ formattedMonth +" "+ formattedDay +" "+ formattedTime +" "+ formatWhen);

        double ts4Temp = ts4.getTemp(formattedYear, formattedMonth, formattedDay, formattedTime, formattedWhen); //get temp of TS4
        double ts4TempFahrenheit = (((ts4Temp * 10) * 9/5) + 32); // 1/10 Celsius to Fahrenheit conversion

        return ts4TempFahrenheit;
    }
}
